### ISSUE TITLE
code problem 

### ISSUE THREAD

**Issue by Tongzhao11** [HCPLab-SYSU/SR#4]
I can not run the test code successfully. The error is ：
Traceback (most recent call last):
  File "test.py", line 251, in <module>
    main()
  File "test.py", line 118, in main
    validate(test_loader, model, criterion, fnames)
  File "test.py", line 162, in validate
    output = model(union_var, obj1_var, obj2_var, bpos_var, full_im_var, bboxes_var, categories_var)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaotong/01.script/09.social_relationship_prediction/networks/GRM.py", line 80, in forward
    contextual[b, int(idxs[i])+self._num_class, 2:] = rois_feature[start_idx+i, :]
IndexError: index 2 is out of bounds for dimension 0 with size 2

The config of test script is as follows: 

# Path to Images
ImagePath="SR/image/"
# Path to object boxes
ObjectsPath="SR/objects/faster_bboxes_categories_t3/"
# Path to test list
TestList="SR/list/PISC_fine_level_test.txt"
# Path to adjacency matrix
AdjMatrix="SR/adjacencyMatrix/PISC_fine_level_matrix.npy"
# Number of classes
num=6
# Path to save scores
ResultPath="result/"
# Path to model
ModelPath="SR/models/PISC_fine_level.pth.tar"
echo $ModelPath

python test.py $ImagePath $ObjectsPath $TestList --weight $ModelPath --adjacency-matrix $AdjMatrix -n $num -b 1 --print-freq 100 --write-out --result-path $ResultPath

The image name is '06017.jpg'
I found that the shape of roi feature is [2, 2048], but the  cur_rois_num is 4. Thus, 
an error occurred when assignment in 'contextual[b, int(idxs[i])+self._num_class, 2:] = rois_feature[start_idx+i, :]' in GRM.py

why??

**Comment by LeviAckermann** [comment]
I canceled the data parallel processing mode, then it is successful

**Comment by jiangjing0819** [comment]
Can this code run out of the final recognized image besides the comparative data of various methods?

**Comment by waxnkw** [comment]
When applying DataParallel to model.full_im_net, the full_im_net will scatter every param into several part. However, only one param rois need to be divided. You can use  "rois_feature = self.full_im_net(full_im.repeat(gpu_num, 1,1,1), rois, categories.repeat(gpu_num, 1))" to generate rois_feature instead in GRM.
